AWSTemplateFormatVersion: 2010-09-09

Description: A template to create ECR

#-------------------------------------------------------------#
# Parameters
#-------------------------------------------------------------#
Parameters:
  # Required parameters
  Project:
    Description: The project name
    Type: String
    Default: kasa
  
  EnvCode:
    Description: The environment code
    Type: String
    Default: dev
    AllowedValues:
        - dev
        - stg
        - prd

  # Optional parameters
  RepositoryName:
    Description: The repository name
    Type: String
    Default: api

#-------------------------------------------------------------#
# Resources
#-------------------------------------------------------------#
Resources:
  #-----------------------------------------------------------#
  # ECR repository
  #-----------------------------------------------------------#
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${Project}-${EnvCode}-${RepositoryName}-ecr
      ImageScanningConfiguration:
        scanOnPush: true
      LifecyclePolicy: 
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "For all images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }